name: eschernet
channels:
  - xformers
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.2=py39h22a60cf_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_1
  - numpy-base=1.25.0=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.2.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - pytorch=2.0.0=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.0=py39_cu118
  - torchtriton=2.0.0=py39
  - torchvision=0.15.0=py39_cu118
  - typing_extensions=4.7.1=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xformers=0.0.19=py39_cu11.8.0_pyt2.0.0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.23.0
    - addict==2.4.0
    - aiofiles==23.1.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - albumentations==0.4.3
    - altair==4.2.2
    - annotated-types==0.5.0
    - ansi2html==1.8.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - asyncer==0.0.2
    - attrs==23.1.0
    - backcall==0.2.0
    - blinker==1.6.2
    - braceexpand==0.1.7
    - cachetools==5.3.1
    - carvekit-colab==4.1.0
    - click==8.1.6
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.1.4
    - configargparse==1.7
    - contourpy==1.1.0
    - controlnet-aux==0.0.7
    - cycler==0.11.0
    - dash==2.12.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - dataclasses-json==0.6.1
    - datasets==2.4.0
    - dearpygui==1.10.1
    - decorator==4.4.2
    - deprecated==1.2.14
    - diffusers==0.19.3
    - dill==0.3.5.1
    - docker-pycreds==0.4.0
    - easydict==1.10
    - einops==0.3.0
    - entrypoints==0.4
    - envlight==0.1.0
    - exceptiongroup==1.1.2
    - executing==2.0.0
    - fastapi==0.100.1
    - fastcore==1.5.29
    - fastjsonschema==2.18.0
    - ffmpy==0.3.1
    - filetype==1.2.0
    - fire==0.4.0
    - flask==2.2.5
    - flatbuffers==23.5.26
    - fonttools==4.41.1
    - freetype-py==2.4.0
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - ftfy==6.1.1
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.32
    - glfw==2.6.2
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - gradio==3.21.0
    - grpcio==1.56.2
    - h11==0.14.0
    - h5py==3.10.0
    - hjson==3.1.0
    - httpcore==0.17.3
    - httpx==0.24.1
    - huggingface-hub==0.16.4
    - humanfriendly==10.0
    - imageio==2.32.0
    - imageio-ffmpeg==0.4.8
    - imgaug==0.2.6
    - imgviz==1.7.3
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - iniconfig==2.0.0
    - inquirerpy==0.3.4
    - ipython==8.14.0
    - ipywidgets==8.1.0
    - itsdangerous==2.1.2
    - jaxtyping==0.2.23
    - jedi==0.18.2
    - joblib==1.3.2
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.18.4
    - jsonschema-specifications==2023.7.1
    - jupyter-core==5.3.1
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.4
    - kornia==0.6.0
    - lazy-loader==0.3
    - libigl==2.4.1
    - lightning-utilities==0.9.0
    - linkify-it-py==2.0.2
    - llvmlite==0.41.1
    - loguru==0.7.0
    - lovely-numpy==0.2.9
    - lovely-tensors==0.1.15
    - lpips==0.1.4
    - markdown==3.4.4
    - markdown-it-py==2.2.0
    - marshmallow==3.20.1
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mesh2sdf==1.1.0
    - modelcards==0.1.6
    - moviepy==1.0.3
    - multidict==6.0.4
    - multiprocess==0.70.13
    - mypy-extensions==1.0.0
    - nbformat==5.5.0
    - nerfacc==0.5.2
    - nest-asyncio==1.5.7
    - ninja==1.11.1
    - numba==0.58.1
    - numpy==1.24.4
    - oauthlib==3.2.2
    - objprint==0.2.3
    - omegaconf==2.3.0
    - onnxruntime==1.16.1
    - onnxruntime-gpu==1.16.1
    - open-clip-torch==2.7.0
    - open3d==0.16.0
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.8.0.74
    - orjson==3.9.2
    - packaging==23.1
    - pandas==2.0.3
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pfzy==0.3.4
    - pickleshare==0.7.5
    - pillow==10.0.0
    - piq==0.8.0
    - platformdirs==3.10.0
    - plotly==5.13.1
    - pluggy==1.3.0
    - plyfile==1.0.1
    - pooch==1.7.0
    - proglog==0.1.10
    - prompt-toolkit==3.0.39
    - protobuf==3.20.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pudb==2019.2
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyarrow==12.0.1
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybind11==2.11.1
    - pydantic==1.10.12
    - pydantic-core==2.4.0
    - pydeck==0.8.0
    - pydeprecate==0.3.1
    - pydub==0.25.1
    - pyglet==1.5.0
    - pygltflib==1.16.1
    - pygments==2.15.1
    - pyhocon==0.3.57
    - pymatting==1.1.10
    - pymcubes==0.1.2
    - pymeshlab==2022.2.post4
    - pympler==1.0.1
    - pyopengl==3.1.0
    - pyparsing==3.0.9
    - pypose==0.6.5
    - pyquaternion==0.9.9
    - pyransac3d==0.6.0
    - pyrender==0.1.45
    - pytest==7.4.3
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - pytorch-fid==0.3.0
    - pytorch-ignite==0.4.12
    - pytorch-lightning==1.9.0
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - referencing==0.30.0
    - regex==2023.6.3
    - rembg==2.0.50
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - retrying==1.3.4
    - rich==13.4.2
    - rpds-py==0.9.2
    - rsa==4.9
    - safetensors==0.3.1
    - scikit-image==0.20.0
    - scikit-learn==1.3.0
    - scipy==1.9.1
    - segment-anything==1.0
    - sentencepiece==0.1.99
    - sentry-sdk==1.28.1
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - stack-data==0.6.2
    - starlette==0.27.0
    - streamlit==1.22.0
    - style==1.1.0
    - taming-transformers==0.0.1
    - taming-transformers-rom1504==0.0.6
    - tenacity==8.2.2
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - termcolor==2.3.0
    - test-tube==0.7.5
    - threadpoolctl==3.2.0
    - tifffile==2023.7.18
    - timm==0.9.10
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch-efficient-distloss==0.1.3
    - torch-fidelity==0.3.0
    - torchmetrics==1.2.0
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.30.2
    - trimesh==3.23.5
    - typeguard==2.13.3
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - tzlocal==4.3.1
    - uc-micro-py==1.0.2
    - update==0.0.1
    - urwid==2.1.2
    - uvicorn==0.23.1
    - validators==0.20.0
    - varname==0.12.0
    - visdom==0.2.4
    - wandb==0.15.7
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - webdataset==0.2.5
    - websocket-client==1.6.4
    - websockets==11.0.3
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.8
    - wrapt==1.15.0
    - xatlas==0.0.8
    - xxhash==3.2.0
    - yarl==1.9.2
    - zipp==3.16.2
